### ISSUE TITLE
How to use your plugin

### ISSUE THREAD

**Issue by KOCIU22** [isaozler/grafana-shift-selector#1]
Hello i don't have much experience with mysql can you explain how to use your plugin i have prepare datasource with values but what too do next ? meybe you can prepare some short movie about configuration in grafana ?

![image](https://user-images.githubusercontent.com/78568161/162435457-b94927c2-d349-43f5-9f61-3111c93fc3af.png)

![image](https://user-images.githubusercontent.com/78568161/162435656-a0bd225b-9ed1-4d7f-9661-4654377cd2bd.png)

Best Regard Luke

**Comment by baur** [comment]
Please, look read README file

The plugin works fine! you can use constant variables without a database

Just add the next variable:

![image](https://user-images.githubusercontent.com/2898361/164461030-df5785c8-1e0f-446e-a7ec-6140d87cd25a.png)
with next **value**:

```JSON
{
  "static": {
    "shifts": [
      {
        "group": "Group 1",
        "group_uuid": "group_uuid_1",
        "uuid": "shift_uuid_1",
        "label": "Morning Custom",
        "startTime": "06:00:00",
        "endTime": "14:00:00",
        "order": 1
      },
      {
        "group": "Group 2",
        "group_uuid": "group_uuid_2",
        "uuid": "shift_uuid_2",
        "label": "Afternoon Custom",
        "startTime": "14:00:00",
        "endTime": "22:00:00",
        "order": 1
      },
      {
        "group": "Group 2",
        "group_uuid": "group_uuid_2",
        "uuid": "shift_uuid_3",
        "label": "Night Custom",
        "startTime": "22:00:00",
        "endTime": "06:00:00",
        "order": 2
      }
    ]
  }
}
```
