### ISSUE TITLE
Real Time mode not updating date (but time yes)

### ISSUE THREAD

**Issue by vincent-gou** [isaozler/grafana-shift-selector#10]
Hi, 
I'm using latest release of plugin and it's successfully working on non real time dashboard. 
But on real time mode, day date is not updated automatically (but time shift yes ! :-) ).

For example below screenshot:
Actual date is 12/07/22 and shift plugin with real time activated still display previous day date 11/07/22.

![image](https://user-images.githubusercontent.com/46958513/178437702-e35f54b7-1329-43e9-abfc-70ddc5008186.png)

Shift plugin setup:
![image](https://user-images.githubusercontent.com/46958513/178438031-8371323f-8b7c-4336-b719-6e5a31ad218f.png)

To change current day date, i have to update manually date in panel edit mode and save dashboard afterwards:
![image](https://user-images.githubusercontent.com/46958513/178438741-e73fe57c-8938-4bda-88f0-dcc53c2d8fba.png)

**Comment by baur** [comment]
try update Grafana in some versions was  [bug](https://github.com/grafana/grafana/issues/48652)

**Comment by vincent-gou** [comment]
Currently using v9.0.1 Grafana release. May try to update to v9.0.2.
Thanks

**Comment by baur** [comment]
on v9.0.1 fixed

**Comment by isaozler** [comment]
Hi @portbusy, I did look into it but wasn't able to provide a solution for it yet. I will try to fix it this weekend. Thanks for reminding me.

**Comment by isaozler** [comment]
With the new release v0.1.0 this should be fixed. The plugin is in review by at Grafana, but you can already try it out by downloading the latest release. Please reopen this issue if there are still problems using this feature.

**Comment by smtpl-iiotian** [comment]
I faced the same issue with grafana v9.4.15 where date is not updating on the next day automatically. I set a 24 hours time from 07:00:00 to 06:59:59 with a single group as below.

{
    "static": {
        "shifts": [
            {
                "group": "uuid_1",
                "group_uuid": "group_uuid_1",
                "uuid": "shift_uuid_1",
                "label": "Whole Shift Time",
                "startTime": "07:00:00",
                "endTime": "06:59:59",
                "order": 1
            }
        ]
    }
}

After login and opening the dashboard it took 24 hours time 17/07/2024 07:00:00 to 18/07/2024 06:59:59 along with date as expected. So, Real-time shift auto-select with dashboard refresh interval of 1 minute worked as expected first time after login and opening the dashboard.

To check if the date gets auto-updated the next day, I kept the dashboard opened. But today at 9am it was showing the same date as above and didn't got updated to 18/07/2024 07:00:00 to 19/07/2024 06:59:59. 
I logged out, logged in again and opened the dashboard and then the date got updated to current date.

Please guide, if I am missing something.
