### ISSUE TITLE
stupid questions don't exists.... where to set the variable?

### ISSUE THREAD

**Issue by NAXOS1980** [isaozler/grafana-shift-selector#12]
Hi, 

I have a stupid question.... where do I add the Variable: var_query_map?

is it a standard Grafana variable, but if so which type? 

![image](https://user-images.githubusercontent.com/10358502/189840975-8ab02ae2-cdbe-4ab5-9e39-fadc1df5457c.png)

or do I need to add it to the json model? but how?

**Comment by isaozler** [comment]
Hi @NAXOS1980 you already commented to your first statement in the title, so I'll skip that ;) 

In the readme you have this section... think that will clarify

![image](https://user-images.githubusercontent.com/1378630/189845416-e3089e23-3d75-40a8-aa6f-7a4acfa61a76.png)

**Comment by NAXOS1980** [comment]
Thanks! it is working. 

What went wrong is once the variable is created the panel is not clearing the error message directly.
I needed to edit the panel again before clearing the Error Message. 

Many thanks, For the quick reply!
