### ISSUE TITLE
Auto shift selector not working

### ISSUE THREAD

**Issue by tdekoning93** [isaozler/grafana-shift-selector#16]
Hey,

We wanted to start using the auto shift plugin, hoping it would help with automatically selecting the right shift. It doesn't seem to do that and I have no clue if thats due to us not using it correctly or something else being wrong. It also doesn't seem to change the timeframe even when having the auto refresh set to 5s. 

We are still using Grafana 8.5.20. Any help would be appreciated.

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/22026133/219409524-894f4a73-64ba-4986-b625-a831bb212af9.png">

**Comment by isaozler** [comment]
Hi Tim,

An ongoing bug in the real-time feature prevents the selector from changing shifts. I will refactor the plugin to solve this issue because a quick fix wasn't doable.

I hope to give updates on this as soon as possible.

**Comment by tdekoning93** [comment]
Thanks for the reply. That would be great. Do you have any ETA on this? Don't want to push you, but I saw the last change to the shift selector was 10 months ago, so just curious if it's actively maintained. Then we can switch from your initial version to this published official one, haha.

**Comment by isaozler** [comment]
Just published the new version. With the new release v0.1.0 this should be fixed. Once the review of the plugin is done by Grafana you can directly install it from your dashboard, but in the meanwhile you can try it out by downloading and installing the latest release manually.

**Comment by isaozler** [comment]
@tdekoning93 Eventually refactored the whole codebase 🤣 it took a while to update the plugin. Sorry for that. 

I hope this update helps everyone using this plugin. I will try to maintain the plugin more actively.

**Comment by tdekoning93** [comment]
Thanks a lot! Will try it out. Big kudos from our side to you.

**Comment by isaozler** [comment]
Thanks, Tim! Please let me know if you stumble upon issues. The latest version should be released asap as it is reviewed and approved.

**Comment by G3CK0za** [comment]
Hi @isaozler,

I have tested the plug-in and it does auto-select the shifts now. However, if I have auto-refresh set for the dashboard, the plug-in turns it off on shift change. Any idea what could be causing this?

**Comment by Sourve** [comment]
/src/module.ts file seems to be missing a reference to the refreshInterval variable that is showcased in the README file. This would be added with code similar to below:

```
.addTextInput({
      category: ['Behavior'],
      path: 'refreshInterval',
      showIf: (c: any) => c.isAutoSelectShift,
      name: 'Custom refresh interval',
      description:
        'Determine a custom dashboard refresh interval. The global refresh interval will overwrite this value',
      defaultValue: '5s',
    })
```

Not having this option is causing the panel to set the refresh interval to 'false' instead of a specified value. If i am mistaken on how to set the refresh interval please let me know. I have not worked with grafana plugins or compiling them so I cannot currently test if the code segment would fix this issue, I will try to test this if @isaozler doesn't respond.

**Comment by isaozler** [comment]
Thanks @Sourve I'll check next week if this resolves the issue.

**Comment by fatbasstard** [comment]
Another interesting thing related to this. It appears the `Select group` is actually mandatory. Leaving it blank results in the panel not working. Adding the value of the single group and it works

![image](https://github.com/isaozler/grafana-shift-selector/assets/35613489/23a11d02-22ae-47d3-9e97-9a6bf682f0dc)

**Comment by isaozler** [comment]
Thanks for pointing out Frank @fatbasstard 🙏 I will add a fallback so it won't break 👍

**Comment by fatbasstard** [comment]
Any news on the progress @isaozler ? 😄

**Comment by isaozler** [comment]
Following Monday, I will start working again 😅 🏖️

**Comment by isaozler** [comment]
Released an update [see changelog v0.1.3](https://github.com/isaozler/grafana-shift-selector/compare/v0.1.2...v0.1.3)

**Comment by isaozler** [comment]
> /src/module.ts file seems to be missing a reference to the refreshInterval variable that is showcased in the README file. This would be added with code similar to below:
> 
> ```
> .addTextInput({
>       category: ['Behavior'],
>       path: 'refreshInterval',
>       showIf: (c: any) => c.isAutoSelectShift,
>       name: 'Custom refresh interval',
>       description:
>         'Determine a custom dashboard refresh interval. The global refresh interval will overwrite this value',
>       defaultValue: '5s',
>     })
> ```
> 
> Not having this option is causing the panel to set the refresh interval to 'false' instead of a specified value. If i am mistaken on how to set the refresh interval please let me know. I have not worked with grafana plugins or compiling them so I cannot currently test if the code segment would fix this issue, I will try to test this if @isaozler doesn't respond.

@Sourve :
This is done intentionally by Grafana. The refresh rate is automatically discarded when the dashboard has an absolute date range. See https://github.com/grafana/grafana/issues/12105#issuecomment-395137603

I created a workaround so that it's possible to have a refresh rate by selecting the refresh rate from the panel property "Behaviour > Custom refresh interval."

![image](https://github.com/isaozler/grafana-shift-selector/assets/1378630/96c9d232-03b7-464a-9f89-ce2599361774)

**Comment by DasDepp** [comment]
Hi @isaozler,
thank you very much for contributing these nice Grafana Plugin. When there will be the new Grafana Plugin version package available to install it via the Grafana CLI plugin?

**Comment by isaozler** [comment]
It's currently under review by the Grafana Team; as soon as it's approved, it will be available to install. But you could also install it manually (unsigned) for testing. Usually, the review takes little time.

**Comment by fatbasstard** [comment]
Takes long, boring 😉

**Comment by fatbasstard** [comment]
Any news on the Grafana approval @isaozler ?

**Comment by isaozler** [comment]
<img width="802" alt="image" src="https://github.com/isaozler/grafana-shift-selector/assets/1378630/be7f7f86-e699-4361-8491-41ec967e41f7">

I will be keeping an eye on this 👍

**Comment by fatbasstard** [comment]
![image](https://github.com/isaozler/grafana-shift-selector/assets/35613489/5438af90-2fc7-47e9-86e3-3a7be4292c32)

😛

**Comment by G3CK0za** [comment]
![Sad-Pablo-Escobar](https://github.com/isaozler/grafana-shift-selector/assets/120001853/9c13b80d-cc89-41ea-8a84-43c91f6631d0)

**Comment by fatbasstard** [comment]
Am poking through Grafana support, our contacts at Grafana and everything.. You have a clue what's going on @isaozler ?

**Comment by isaozler** [comment]
I saw it was pending a new release because there was an issue. I have to submit a fixed version for a new review 😞 I will see if I can submit a new version by tomorrow.

**Comment by fatbasstard** [comment]
Any updates on the progress @isaozler ?

**Comment by isaozler** [comment]
👋 @fatbasstard Frank and all who are waiting, I just submitted the latest release for review at Grafana, containing all the fixes addressed by the Grafana Team. I know it took some time, but I'm doing my best to help you guys with this plugin.

![image](https://github.com/isaozler/grafana-shift-selector/assets/1378630/23fc9ff8-a352-4dac-adc7-989579aaa4b7)

**Comment by isaozler** [comment]
The latest release 0.1.4 is published 🙏
