### ISSUE TITLE
How do I install 0.1.2 version ?

### ISSUE THREAD

**Issue by misiek303** [isaozler/grafana-shift-selector#19]
Just downloading the files to the folder does not work. Grafana complains about the signature.

**Comment by isaozler** [comment]
I would recommend installing the signed version which is available in the plugins section of your Grafana dashboard. This update has no breaking changes.

But if you explicitely need thus version you should configure your Grafana install to allow unsigned plugins.

**Comment by misiek303** [comment]
He last available version is 0.0.3 . I did update the Grafana to the latest version 9.5.x but it didn’t update plugins repos. How to do it ?

**Comment by baur** [comment]
> He last available version is 0.0.3 . I did update the Grafana to the latest version 9.5.x but it didn’t update plugins repos. How to do it ?

- Download [zip](https://github.com/isaozler/grafana-shift-selector/releases/download/v0.1.2/isaozler-shiftselector-panel-0.1.2.zip)  file
- Extract into data/plugins
- Restart grafana

**Comment by misiek303** [comment]
The installation finally worked. Thanks.
