### ISSUE TITLE
Hide select date section and set to shifts any date ranges 

### ISSUE THREAD

**Issue by baur** [isaozler/grafana-shift-selector#2]
Hi, good job 👍, just what I've been looking for 💡

Is it possible to hide the select date (day) section and set to shifts section any date ranges (without icons):
for example:
1 q, 2 q, March, April, May etc

Long time I'm using [this plugin](https://github.com/WilliamVenner/grafana-timepicker-buttons), but not working on 8.5

**Comment by isaozler** [comment]
> Hi, good job 👍, just what I've been looking for 💡
> 
> Is it possible to hide the select date (day) section and set to shifts section any date ranges (without icons): for example: 1 q, 2 q, March, April, May etc
> 
> Long time I'm using [this plugin](https://github.com/WilliamVenner/grafana-timepicker-buttons), but not working on 8.5

With the upcoming release you will be able to hide the select day.

Your request of having date ranges with the shift buttons, need a bit more refinement.

I will get back to this.

**Comment by baur** [comment]
Thank you, Will wait!!!

**Comment by baur** [comment]
Thank you, Will wait!!!
