### ISSUE TITLE
Immediately apply some shift by default (on load)

### ISSUE THREAD

**Issue by baur** [isaozler/grafana-shift-selector#3]
Hi, 
It would be nice if immediately apply some shift by default (on load)

Mode1:
Set default shift (constant)

Mode2:
Apply shift which matches with system hour:

For example
s1 > 00:00 - 08:00
s2 > 08:00 - 16:00
s3 > 16:00 - 24:00

System time is 07:00 -> apply s1
System time is 15:55 -> apply s2
System time is 22:15 -> apply s3

**Comment by baur** [comment]
and apply default (or system time) shift on dateSelect

**Comment by isaozler** [comment]
Hi Bauyrzhan,

There is a new feature in the new release. You can enable "realtime tracking" that will meet your expectations I think.

When realtime is enabled, it checks the panel every determined interval time which shift the now is in and applies it.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/1378630/165486397-69282cf4-1479-45f5-8fa3-7ee8fc43c8f0.png">

With the release of 0.0.3 this feature will be available.

**Comment by baur** [comment]
Real-time Tracking is very useful in kiosk mode! 

But in my case we needs auto select shift (auto select - according to system time, not time picker) on dashboard load only (first open) then the user should be able to select other dates and shifts for analytics

**Comment by isaozler** [comment]
This should be fixed in version v0.1.0. Feel free to reopen if it's not exactly what you need.

**Comment by Naruske** [comment]
> This should be fixed in version v0.1.0. Feel free to reopen if it's not exactly what you need.

What exactly was fixed or added here? I too have an issue where my date does not default to today. I'm fine with manually picking my shift to be fair. I'm kind of looking for the realtime shift selector but with option to check previous days+shifts
