### ISSUE TITLE
Error! Datasource `Shifts Data Model` not found! 

### ISSUE THREAD

**Issue by fatbasstard** [isaozler/grafana-shift-selector#33]
When upgrading Grafana from 9.5.14 to 10.3.3 the Shift Selector starting throwing errors:

![image](https://github.com/isaozler/grafana-shift-selector/assets/35613489/17b483b8-3fa3-4eaa-ba05-25aafee4b03f)

**Comment by isaozler** [comment]
Resolved within https://github.com/isaozler/grafana-shift-selector/issues/26
