### ISSUE TITLE
Version 1.6 not published

### ISSUE THREAD

**Issue by fatbasstard** [isaozler/grafana-shift-selector#37]
Hi,

I Noticed the latest version (1.6) is still not published: https://grafana.com/grafana/plugins/isaozler-shiftselector-panel/

**Comment by isaozler** [comment]
Hi Frank,

I see it's still in progress indeed, but there is an issue with the plugin submission page. I will follow up on this.

https://grafana.slack.com/archives/C3HJV5PNE/p1716379228787789

**Comment by isaozler** [comment]
I had to change the workflow release action that was signing the package and creating a MANIFEST.txt file in the dist.

https://github.com/isaozler/grafana-shift-selector/commit/a8a9da91f63b3747ee83ec68db2032a815961d8d

Resubmitted the valid package, David H. from Grafana validated the package. Waiting for the release at this point.

**Comment by isaozler** [comment]
Thanks for the notice @fatbasstard 🙏

**Comment by isaozler** [comment]
Version 0.1.6 is now published.

There was an issue with the static datasets that needed fixing. Sorry for letting you wait this long.
