### ISSUE TITLE
Date selection options 

### ISSUE THREAD

**Issue by baur** [isaozler/grafana-shift-selector#4]
Would be very nice if add the next options to **Date selection**

1.
Optional text (localization)

![image](https://user-images.githubusercontent.com/2898361/164459023-82650502-bd02-4a54-babf-c31d8a779322.png)

2. 
- Set default value 
- Show and hide option (hide the whole section and apply default value (if not null) else first value **two dots**). 

![image](https://user-images.githubusercontent.com/2898361/164459308-7dfc6b82-700b-4e27-a8d9-c49cf6d06fe8.png)

**Comment by isaozler** [comment]
Hi Bauyrzhan, updated the plugin to have 3 options for the range buttons. You can set it to text, icon only or text and icon.
Hope this helps.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/1378630/165485949-7680d2bb-5d66-4841-9d28-4665816833fe.png">


<img width="341" alt="image" src="https://user-images.githubusercontent.com/1378630/165485833-b90c027f-56ff-4c6e-8832-d574445d4557.png">
<img width="228" alt="image" src="https://user-images.githubusercontent.com/1378630/165485875-ded13036-0587-4758-ba88-53249c2d4f4f.png">
<img width="161" alt="image" src="https://user-images.githubusercontent.com/1378630/165485899-8b1f31b0-4392-4a45-8b41-79a2657764af.png">

**Comment by baur** [comment]
Thank you! good job!

In our case, only **Start-End** is relevant, so it would be cool if we can hide the section completely

![image](https://user-images.githubusercontent.com/2898361/165666720-2b9c56bf-e812-45c1-ad86-e3304ce0db9f.png)

and is it possible centerate date value and add right margin on text label?

![image](https://user-images.githubusercontent.com/2898361/165667313-ba7aea5b-7670-43d5-89bd-75ce1e69b5d3.png)

**Comment by isaozler** [comment]
Knowing from other usecases that this should stay visible, will be leaving this issue open to see if there are others who need this

**Comment by pax0r** [comment]
+1 I would like to hide this option entirely if possible

**Comment by isaozler** [comment]
added the option to hide the date selector or just the range buttons from the panel (v0.1.1)
