### ISSUE TITLE
Some ideas for improvements and some question regarding refresh

### ISSUE THREAD

**Issue by DrAndersBjork** [isaozler/grafana-shift-selector#6]
A very nice plugin that helps to solve a problem with setting the time ranges more easily!

I have some suggestions for improvement both of the plugin and the description text.
1. Add text in description text that it is under "Panel Options, Repeat options, Repeat by variable" is where the var_query_map needs to be set. 
2. It would be nice also to be able to set a number of days or hour for a "shift" as span for a group. 
3. For me at least I can not change month in the day selection, other than typing in the new date. Is it possible to add an arrow to shift month in the calendar.

I do not know if this is an unwanted feature of grafana or if I have missed something in the installation. In order to get my dashboard to update after pressing a button in the plugin panel I need to press refresh in order refresh the dashboard. 
Any ideas on this?

**Comment by isaozler** [comment]
Based on your feedback, I moved some variable settings to the panel to make it easier to configure. You can find it in the v0.1.0 release.

The arrows in the date-picker is a dependency package issue, will fix it in the next release v0.1.1
